services:
  - type: web
    name: cu-chatbot-backend
    env: python
    rootDir: cu-chatbot-backend
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('wordnet')"
    startCommand: gunicorn app:app
    plan: free
